export const reducerActions = {
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  REMOVE_ITEM: "REMOVE_ITEM",
  INITIALIZE_CART_ITEMS: "INITIALIZE_CART_ITEMS",
};
